### ISSUE TITLE
Release roadmap

### ISSUE THREAD

**Issue by mythmakerseven** [mythmakerseven/ostrakon#1]
Okay it's time to make the final checklist for things to do before publicly sharing this with people.

- [x] drag and drop from the results list
- [x] make the different sections of the sidebar collapsible
  - [x] add an informational section, like a how-to, FAQ, changelog, etc.
- [x] for mobile screens, split the sidebar into two menus (one for adding items, one with chart options) and use floating toggle buttons to open them
- [x] refresh the options form values when the user switches charts
- [x] background image support
- [x] fix the crunched top bar on mobile
- [x] fix the styling issue that causes scrolling in the main view on small laptop screen sizes

**Comment by mythmakerseven** [comment]
wow I did half of these things yesterday
